 rm(list=ls())
source("emc/emc.R")
source("models/DDM/DDM/ddmTZD.R")
load("sPNAS_a.RData")
# sPNAS_a_burn <- run_chains(samplers,iter=c(1000,0,0),cores_per_chain=10)
# save(samplers,sPNAS_a_burn,file="sPNAS_a.RData")
sPNAS_a_adapt <- run_chains(sPNAS_a_burn,iter=c(0,2000,0),cores_per_chain=10)
save(samplers,sPNAS_a_burn,sPNAS_a_adapt,file="sPNAS_a.RData")
# sPNAS_a_sample <- run_chains(sPNAS_a_adapt,iter=c(0,0,1000),cores_per_chain=10)
# save(samplers,sPNAS_a_burn,sPNAS_a_adapt,sPNAS_a_sample,file="sPNAS_a.RData")
# ppPNAS_a <- post_predict(sPNAS_a_sample,n_cores=19)
# save(samplers,sPNAS_a_burn,sPNAS_a_adapt,sPNAS_a_sample,ppPNAS_a,file="sPNAS_a.RData")
